### PR TITLE
html skeleton

### PR DESCRIPTION
**Pull request by smrogers93**
We don't have anything else so..................

### CODE REVIEW

**Comment by sbstiane46** [comment]
Lets give it a try.

**Review by swilliams2077 — APPROVED** [review]
Nice!!!

**Comment by swilliams2077** [comment]
Only advice is to comment on your code next time. Thats a must for everyone so we won't have to decipher it too much.

**Review by sbstiane46 — APPROVED** [review]

**Comment by dziubliukbm** [comment]
first experience with this ...

**Pull request merged**
